### ISSUE TITLE
Category Folder Mishandled

### ISSUE THREAD

**Issue by rdelian** [sadboilogan/savereload#1]
Script _fails_ to restart the correct resource if the resource it's in a [category] folder.
File path: `Z:\fivem_server\server-data\resources\[Gamemode]\racegm\helpers\specific.lua`

It restarted all resources inside `[Gamemode]`

**Comment by logan-mcgee** [comment]
huh, thought I fixed that issue, I'll look into it, cheers.

**Comment by logan-mcgee** [comment]
issue seems to be fixed, lemme know if it still happens.

**Comment by rdelian** [comment]
All good now 🚀
